- name: Ensure required packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ yum_packages }}"

- name: Remove repository (and clean up left-over metadata)
  yum_repository:
    name: epel.repo
    state: absent
  notify: yum-clean-metadata

- name: DownLoad OKD 3.6 playbooks from https://github.com/openshift/openshift-ansible
  git:
    repo: 'https://github.com/openshift/openshift-ansible'
    dest: release-3.6
    version: release-3.6
    clone: yes
    update: no
